app/views/sub.py
import datetime
import time
from flask import Blueprint, redirect, url_for, abort, render_template, request, Response
from flask_login import login_required, current_user
from feedgen.feed import FeedGenerator
from peewee import fn, JOIN
from ..misc import engine
from ..models import Sub, SubMetadata, SubStylesheet, SubUploads, SubPostComment, SubPost, SubPostPollOption
from ..models import SubPostPollVote, SubPostMetadata, SubFlair, SubLog, User, UserSaved, SubMod, SubBan
from ..forms import EditSubFlair, EditSubForm, EditSubCSSForm, EditSubTextPostForm, EditMod2Form
from ..forms import EditSubLinkPostForm, BanUserSubForm, EditPostFlair, CreateSubFlair, PostComment
from .. import misc

sub = Blueprint('sub', __name__)


@sub.route("/<sub>/")
@sub.route("/<sub>")
def view_sub(sub):
    """ Here we can view subs """
    if sub.lower() == "all":
        return redirect(url_for('all_hot', page=1))

    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    try:
        x = SubMetadata.select().where(SubMetadata.sid == sub.sid)
        x = x.where(SubMetadata.key == 'sort').get()
        x = x.value
    except SubMetadata.DoesNotExist:
        x = 'v'
    if x == 'v':
        return redirect(url_for('sub.view_sub_hot', sub=sub.name))
    elif x == 'v_two':
        return redirect(url_for('sub.view_sub_new', sub=sub.name))
    elif x == 'v_three':
        return redirect(url_for('sub.view_sub_top', sub=sub.name))


@sub.route("/<sub>/edit/css")
@login_required
def edit_sub_css(sub):
    """ Here we can edit sub info and settings """
    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    if not current_user.is_mod(sub.sid, 1) and not current_user.is_admin():
        abort(403)

    c = SubStylesheet.get(SubStylesheet.sid == sub.sid)

    form = EditSubCSSForm(css=c.source)
    stor = 0
    ufiles = SubUploads.select().where(SubUploads.sid == sub.sid)
    for uf in ufiles:
        stor += uf.size / 1024

    return engine.get_template('sub/css.html').render({'sub': sub, 'form': form, 'error': False, 'storage': int(stor), 'files': ufiles})


@sub.route("/<sub>/edit/flairs")
@login_required
def edit_sub_flairs(sub):
    """ Here we manage the sub's flairs. """
    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    if not current_user.is_mod(sub.sid, 1) and not current_user.is_admin():
        abort(403)

    flairs = SubFlair.select().where(SubFlair.sid == sub.sid).dicts()
    formflairs = []
    for flair in flairs:
        formflairs.append(EditSubFlair(flair=flair['xid'], text=flair['text']))
    return render_template('editflairs.html', sub=sub, flairs=formflairs,
                           createflair=CreateSubFlair())


@sub.route("/<sub>/edit")
@login_required
def edit_sub(sub):
    """ Here we can edit sub info and settings """
    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    if current_user.is_mod(sub.sid, 1) or current_user.is_admin():
        submeta = misc.metadata_to_dict(SubMetadata.select().where(SubMetadata.sid == sub.sid))
        form = EditSubForm()
        # pre-populate the form.
        form.subsort.data = submeta.get('sort')
        form.sidebar.data = sub.sidebar
        form.title.data = sub.title

        return render_template('editsub.html', sub=sub, editsubform=form, metadata=submeta)
    else:
        abort(403)


@sub.route("/<sub>/sublog", defaults={'page': 1})
@sub.route("/<sub>/sublog/<int:page>")
def view_sublog(sub, page):
    """ Here we can see a log of mod/admin activity in the sub """
    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    logs = SubLog.select().where(SubLog.sid == sub.sid).order_by(SubLog.lid.desc()).paginate(page, 50)
    return engine.get_template('sub/log.html').render({'sub': sub, 'logs': logs, 'page': page})


@sub.route("/<sub>/mods")
@login_required
def edit_sub_mods(sub):
    """ Here we can edit moderators for a sub """
    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    if current_user.is_mod(sub.sid, 2) or current_user.is_modinv(sub.sid) or current_user.is_admin():
        subdata = misc.getSubData(sub.sid, extra=True)
        subMods = misc.getSubMods(sub.sid)
        modInvites = SubMod.select(User.name, SubMod.power_level).join(User).where((SubMod.sid == sub.sid) & (SubMod.invite == True))
        return render_template('submods.html', sub=sub, subdata=subdata,
                               editmod2form=EditMod2Form(), subMods=subMods, subModInvites=modInvites,
                               banuserform=BanUserSubForm())
    else:
        abort(403)


@sub.route("/<sub>/new.rss")
def sub_new_rss(sub):
    """ RSS feed for /sub/new """
    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    fg = FeedGenerator()
    fg.id(request.url)
    fg.title('New posts from ' + sub.name)
    fg.link(href=request.url_root, rel='alternate')
    fg.link(href=request.url, rel='self')
    
    posts = misc.getPostList(misc.postListQueryBase(noAllFilter=True).where(Sub.sid == sub.sid),
                            'new', 1).dicts()

    return Response(misc.populate_feed(fg, posts).atom_str(pretty=True), mimetype='application/atom+xml')


@sub.route("/<sub>/new", defaults={'page': 1})
@sub.route("/<sub>/new/<int:page>")
def view_sub_new(sub, page):
    """ The index page, all posts sorted as most recent posted first """
    if sub.lower() == "all":
        return redirect(url_for('all_new', page=1))

    try:
        sub = Sub.select().where(fn.Lower(Sub.name) == sub.lower()).dicts().get()
    except Sub.DoesNotExist:
        abort(404)

    posts = misc.getPostList(misc.postListQueryBase(noAllFilter=True).where(Sub.sid == sub['sid']),
                             'new', page).dicts()

    try:
        vm = SubMetadata.select().where(SubMetadata.sid == sub['sid']).where(SubMetadata.key == 'videomode').get().value
    except SubMetadata.DoesNotExist:
        vm = 0
    playlist = []
    if vm == '1':
        for post in posts:
            if post['link']:
                yid = misc.getYoutubeID(post['link'])
                if yid is not None:
                    playlist.append(yid)

    return engine.get_template('sub.html').render({'sub': sub, 'subInfo': misc.getSubData(sub['sid']), 'playlist': playlist,
                                                   'posts': posts, 'page': page, 'sort_type': 'sub.view_sub_new',
                                                   'subMods': misc.getSubMods(sub['sid'])})


@sub.route("/<sub>/bannedusers")
def view_sub_bans(sub):
    """ See banned users for the sub """
    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    user = User.alias()
    created_by = User.alias()
    banned = SubBan.select(user, created_by, SubBan.created, SubBan.reason, SubBan.expires)
    banned = banned.join(user, on=SubBan.uid).switch(SubBan).join(created_by, JOIN.LEFT_OUTER, on=SubBan.created_by_id)
    banned = banned.where((SubBan.sid == sub.sid) & ((SubBan.effective == True) & ((SubBan.expires.is_null(True)) | (SubBan.expires > datetime.datetime.utcnow()) )))
    banned = banned.order_by(SubBan.created.is_null(True), SubBan.created.desc())

    xbans = SubBan.select(user, created_by, SubBan.created, SubBan.reason, SubBan.expires)
    xbans = xbans.join(user, on=SubBan.uid).switch(SubBan).join(created_by, JOIN.LEFT_OUTER, on=SubBan.created_by_id)
    
    xbans = xbans.where(SubBan.sid == sub.sid)
    xbans = xbans.where((SubBan.effective == False) | ((SubBan.expires.is_null(False)) & (SubBan.expires < datetime.datetime.utcnow()) ))
    xbans = xbans.order_by(SubBan.created.is_null(True), SubBan.created.desc(), SubBan.expires.asc())

    return engine.get_template('sub/bans.html').render({'sub': sub, 'banned': banned, 'xbans': xbans,
                                                        'banuserform': BanUserSubForm(), 'submods': misc.getSubMods(sub.sid)})


@sub.route("/<sub>/top", defaults={'page': 1})
@sub.route("/<sub>/top/<int:page>")
def view_sub_top(sub, page):
    """ The index page, /top sorting """
    if sub.lower() == "all":
        return redirect(url_for('all_top', page=1))

    try:
        sub = Sub.select().where(fn.Lower(Sub.name) == sub.lower()).dicts().get()
    except Sub.DoesNotExist:
        abort(404)

    posts = misc.getPostList(misc.postListQueryBase(noAllFilter=True).where(Sub.sid == sub['sid']),
                             'top', page).dicts()

    try:
        vm = SubMetadata.select().where(SubMetadata.sid == sub['sid']).where(SubMetadata.key == 'videomode').get().value
    except SubMetadata.DoesNotExist:
        vm = 0
    playlist = []
    if vm == '1':
        for post in posts:
            if post['link']:
                yid = misc.getYoutubeID(post['link'])
                if yid is not None:
                    playlist.append(yid)

    return engine.get_template('sub.html').render({'sub': sub, 'subInfo': misc.getSubData(sub['sid']), 'playlist': playlist,
                                                   'posts': posts, 'page': page, 'sort_type': 'sub.view_sub_top',
                                                   'subMods': misc.getSubMods(sub['sid'])})


@sub.route("/<sub>/hot", defaults={'page': 1})
@sub.route("/<sub>/hot/<int:page>")
def view_sub_hot(sub, page):
    """ The index page, /hot sorting """
    if sub.lower() == "all":
        return redirect(url_for('all_hot', page=1))
    try:
        sub = Sub.select().where(fn.Lower(Sub.name) == sub.lower()).dicts().get()
    except Sub.DoesNotExist:
        abort(404)

app/templates/messages/commreply.html
{% extends "layout.html" %}
{% block title %}My messages | {{config.site.lema}}{% endblock %}

{% block navbar %}
{% endblock %}

{% block sidebar %}
{{ super() }}
{% include 'messages/sidebar.html' %}
{% endblock %}

{% block content %}
{{ super() }}
<div id="center-container">
  <div class="inbox content">
    <div class="user-activity col-12">
      <h3><span class="p-icon" data-icon="mail" style="display: inline-block;"></span> Comment Replies</h3>
      {% for message in messages %}
        <article class="pmessage post" data-cid="{{message.mlink}}">
          <div class="main">
            <div class="pull left votecomment" style="margin-right: 10px;">
                <div title="Upvote" class="c-upvote{%if message.positive == True %} upvoted{%endif%}" data-icon="upvote"></div>
                <div title="Downvote" class="c-downvote{%if message.positive == False %} downvoted{%endif%}" data-icon="downvote"></div>
            </div>
            <p class="title"><a href="{{url_for('view_comment_inbox', cid=message.mlink)}}">{{message.subject}}</a></p>
            <p class="container">{{markdown(message.content)|safe}}</p>
            <p class="author"><b><span class="cscore">{{message.score}}</span></b> points, <time-ago datetime="{{message.posted.isoformat()}}Z"></time-ago></p>
            <p class="container">

              <a href="{{url_for('view_user', user=message.username)}}" class="btn small">/u/{{message.username}}</a>
              {% if not message.read %}
                <a class="newmsg" data-mid="{{message.mid}}">new</a>
              {% else %}
                <a data-mid="{{message.mid}}">read <time-ago datetime="{{message.read.isoformat()}}Z"></time-ago></a>
              {% endif %}
              <a href="#comment-form" class="replycom" data-sub="{{message.sub}}" data-replyto='{{message.username}}' data-post='{{message.pid}}' data-parentid='{{message.mlink}}' data-replytitle='{{message.subject}}' data-mid='{{message.mid}}'>reply</a>
              <a href="{{ url_for('view_comment_inbox', cid=message.mlink) }}" class="btn small">permalink</a>
              <!--<a class="savemsg" data-mid="{{message.mid}}">save</a>-->
              <a class="deletemsg" data-mid="{{message.mid}}">delete</a>
              <a class="block" data-uid="{{message.sentby}}">{% if message.sentby not in func.get_ignores(current_user.uid) %}block{%else%}unblock{%endif%}</a>
            </p>
          </div>
          <div id="replyto{{message.mid}}"><div>
        </article>
      {% endfor %}
    </div>
    {% include 'messages/nav.html' %}
  </div>
</div>

<div id="msgpop" style="display:none;">
  <span class="closemsg">&times;</span>
  <div class="modal-content">
    <form data-reset="true" method="POST" data-redir='true' action="{{url_for('do.create_comment', sub='0', pid='0')}}" class="ajaxform comment-form pure-form pure-form-aligned" id="comment-form">
      {% set commentform = form.PostComment()%}
      {{commentform.csrf_token}}
      {{commentform.post()}}
      {{commentform.parent(value='0')}}
      <h3>Reply to comment from <span id="from"></span> in /{{config.site.sub_prefix}}/<span id="sub"></span></h3>
      <fieldset>
        <div class="pure-control-group markdown-editor">
          {{commentform.comment(placeholder="Styling with Markdown format is supported.", rows="10", **{'data-provide' :"markdown"})}}
        </div>
        <div class="pure-controls">
          {% if error %}
            <div class="error">{{error}}</div>
          {%endif%}
          <button type="submit" id="msg-btnsubmit" class="pure-button pure-button-primary" data-prog="Sending...">Send Comment</button>
        </div>
      </fieldset>
    </form>
  </div>
</div>
{% endblock %}

app/templates/messages/ignores.html
{% extends "layout.html" %}
{% block title %}Blocked users | {{config.site.lema}}{% endblock %}

{% block navbar %}
{% endblock %}

{% block sidebar %}
{{ super() }}
{% include 'messages/sidebar.html' %}
{% endblock %}

{% block content %}
{{ super() }}
<div id="container">
  {% if igns %}

    {% for ig in igns %}
    <li><span class="postflair">{{func.getUser(ig).name}}</span>
      <form  method="POST" data-reload="true" action="{{url_for('do.ignore_user', uid=ig)}}" class="ajaxform" style="display: inline-block; margin-left: 1em; margin-top: 5px;">
      <button type="submit" class="pure-button button-xsmall" id="editsub-btnsubmit" data-prog="Deleting..." data-success="Deleted!">Delete</button></form>
    {% endfor %}
  {% else %}
  <h4>You haven't blocked anybody</h4>
  You can block users from the inbox.
  {%endif%}
</div>
{% endblock %}

app/templates/messages/messages.html
{% extends "layout.html" %}
{% block title %}My messages | {{config.site.lema}}{% endblock %}

{% block navbar %}
{% endblock %}

{% block sidebar %}
{{ super() }}
{% include 'messages/sidebar.html' %}
{% endblock %}

{% block content %}
{{ super() }}
<div id="center-container">
  <div class="inbox content">
    <div class="user-activity col-12">
      <h3 style="display: inline-block;"><span class="p-icon" data-icon="mail" style="display: inline-block;"></span> {{box_name}}</h3>
      - <span class="links"><a data-bid="{{boxID}}" class="markall">Mark all as read</a></span>
      {% for message in messages %}
        <article class="pmessage post{% if not message.read %} newmsg{% endif %}">
          <div class="main">
            <p class="title">{{message.subject}}</p>
            <p class="container">{{markdown(message.content)|safe}}</p>
            <p class="author"><time-ago datetime="{{message.posted.isoformat()}}Z"></time-ago></p>
            <p class="container">
              {% if message.username %}
              <a href="{{url_for('view_user', user=message.username)}}" class="btn small">/u/{{message.username}}</a>
              {%else%}
              <a href="#" class="btn small">Phuks</a>
              {%endif%}
              {% if message.read %}
                <a class="read">read <time-ago datetime="{{message.read.isoformat()}}Z"></time-ago></a>
              {% else %}
                {% if message.mtype == 8 %}
                  <a class="" data-mid="{{message.mid}}">new</a>
                {%else%}
                  <a class="readmsg" data-mid="{{message.mid}}">mark as read</a>
                {%endif%}
              {% endif %}
              {% if message.username %}
              <a href="#msg-form" data-mid="{{message.mid}}" data-replyto='{{message.username}}' data-replytitle='{{message.subject}}' class="replymsg">reply</a>
              {%endif%}
              <!--<a class="btn small">forward</a>-->
              <a class="savemsg" data-mid="{{message.mid}}">save</a>
              <a class="deletemsg" data-mid="{{message.mid}}">delete</a>
              <a class="block" data-uid="{{message.sentby}}">{% if message.sentby not in func.get_ignores(current_user.uid) %}block{%else%}unblock{%endif%}</a>
            </p>
          </div>
          <div id="replyto{{message.mid}}"></div>
        </article>
      {% endfor %}
    </div>
    {% include 'messages/nav.html' %}
  </div>
</div>

<div id="msgpop" style="display:none;">
  <span class="closemsg">&times;</span>
  <div class="modal-content">
    <form data-reset="true" id="msg-form" action="{{url_for('do.create_sendmsg')}}" data-redir="{{url_for('inbox_sort')}}" class="pure-form pure-form-aligned ajaxform">
      {% set msgform = form.CreateUserMessageForm()%}
      {{msgform.csrf_token}}
      <h3>Send user message</h3>
      <fieldset>
        <div id="lto" class="pure-control-group">
          <label for="to">User</label>
          {{msgform.to(placeholder=msgform.to.label.text, required=True)}}
        </div>
        <div class="pure-control-group">
          <label for="subject">Subject</label>
          {{msgform.subject(placeholder=msgform.subject.label.text, required=True)}}
        </div>
        <div class="pure-control-group markdown-editor">
          {{msgform.content(placeholder="Styling with Markdown format is supported.", rows="10", **{'data-provide' :"markdown"})}}
        </div>
        <div class="pure-controls">
          {% if error %}
            <div class="error">{{error}}</div>
          {%endif%}
          <button type="submit" id="msg-btnsubmit" class="pure-button pure-button-primary" data-prog="Sending...">Send Message</button>
        </div>
      </fieldset>
    </form>
  </div>
</div>
{% endblock %}

app/templates/messages/modmail.html
{% extends "layout.html" %}
{% block title %}My messages | {{config.site.lema}}{% endblock %}

{% block navbar %}
{% endblock %}

{% block sidebar %}
{{ super() }}
{% include 'messages/sidebar.html' %}
{% endblock %}

{% block content %}
{{ super() }}
<div id="center-container">
  <div class="inbox content">
    <div class="user-activity col-12">
      <h3><span class="p-icon" data-icon="mail" style="display: inline-block;"></span> Modmail</h3>
      {% for message in messages %}
        <article class="pmessage post{% if not message.read %} newmsg{% endif %}" data-replyto='{{message.sentby}}'data-replytitle='Re: {{message.subject}}'>
          <div class="main">
            <p class="title">{{message.subject}}</p>
            <p class="container">{{markdown(message.content)|safe}}</p>
            {% if message.mtype == 2 %}
              <p>Please visit: <a href="{{url_for('sub.edit_sub_mods', sub=message.mlink)}}"> /{{config.site.sub_prefix}}/{{message.mlink}}/mods</a><p>
            {% elif message.mtype == 7 %}
              <p>Please visit: <a href="{{url_for('sub.view_sub_bans', sub=message.mlink)}}"> /{{config.site.sub_prefix}}/{{message.mlink}}/bannedusers</a><p>
            {% endif %}
            <p class="author"><time-ago datetime="{{message.posted.isoformat()}}Z"></time-ago></p>
            <p class="container">
              <a href="{{url_for('view_user', user=message.username)}}" class="btn small">/u/{{message.username}}</a>
              {% if message.read %}
                <a class="read">read <time-ago datetime="{{message.read.isoformat()}}Z"></time-ago></a>
              {% else %}
                <a class="readmsg" data-mid="{{message.mid}}">mark as read</a>
              {% endif %}
              <a href="#msg-form" data-mid="{{message.mid}}" data-replyto='{{message.username}}' data-replytitle='{{message.subject}}' class="replymsg">reply</a>
              <a class="deletemsg" data-mid="{{message.mid}}">delete</a>
            </p>
          </div>
          <div id="replyto{{message.mid}}"><div>
        </article>
      {% endfor %}
    </div>
    {% include 'messages/nav.html' %}
  </div>
</div>

<div id="msgpop" style="display:none;">
  <span class="closemsg">&times;</span>
  <div class="modal-content">
    <form data-reset="true" id="msg-form" action="{{url_for('do.create_sendmsg')}}" data-redir="{{url_for('inbox_sort')}}" class="pure-form pure-form-aligned ajaxform">
      {% set msgform = form.CreateUserMessageForm()%}
      {{msgform.csrf_token}}
      <h3>Send user message</h3>
      <fieldset>
        <div class="pure-control-group">
          <label for="to">User</label>
          {{msgform.to(placeholder=msgform.to.label.text, required=True)}}
        </div>
        <div class="pure-control-group">
          <label for="subject">Subject</label>
          {{msgform.subject(placeholder=msgform.subject.label.text, required=True)}}
        </div>
        <div class="pure-control-group markdown-editor">
          {{msgform.content(placeholder="Styling with Markdown format is supported.", rows="10", **{'data-provide' :"markdown"})}}
        </div>
        <div class="pure-controls">
          {% if error %}
            <div class="error">{{error}}</div>
          {%endif%}
          <button type="submit" id="msg-btnsubmit" class="pure-button pure-button-primary" data-prog="Sending...">Send Message</button>
        </div>
      </fieldset>
    </form>
  </div>
</div>
{% endblock %}

app/templates/messages/nav.html
<div class="msgnav">
  {% if page > 1 %}
    <a href="{{url_for(box_route, page=(page-1))}}" class="pure-button">prev</a>
  {% endif %}
  {% if messages|length == 20 %}
    <a href="{{url_for(box_route, page=(page+1))}}" class="pure-button">next</a>
  {% endif %}
</div>

app/templates/messages/postreply.html
{% extends "layout.html" %}
{% block title %}My messages | {{config.site.lema}}{% endblock %}

{% block navbar %}
{% endblock %}

{% block sidebar %}
{{ super() }}
{% include 'messages/sidebar.html' %}
{% endblock %}

{% block content %}
{{ super() }}
<div id="center-container">
  <div class="inbox content">
    <div class="user-activity col-12">
      <h3><span class="p-icon" data-icon="mail" style="display: inline-block;"></span> Post Replies</h3>
      {% for message in messages %}
        <article class="pmessage post" data-replyto='{{message.username}}' data-post='{{message.pid}}' data-parent='{{message.mlink}}' data-cid="{{message.mlink}}">
          <div class="main">
            <div class="pull left votecomment" style="margin-right: 10px;">
              <div title="Upvote" class="c-upvote{%if message.positive == True %} upvoted{%endif%}" data-icon="upvote"></div>
              <div title="Downvote" class="c-downvote{%if message.positive == False %} downvoted{%endif%}" data-icon="downvote"></div>
          </div>
            <p class="title"><a href="{{url_for('view_comment_inbox', cid=message.mlink)}}">{{message.subject}}</a></p>
            <p class="container">{{markdown(message.content)|safe}}</p>
            <p class="author"><b><span class="cscore">{{message.score}}</span></b> points, <time-ago datetime="{{message.posted.isoformat()}}Z"></time-ago></p>
            <p class="container">
              <a href="{{url_for('view_user', user=message.username)}}" class="btn small">/u/{{message.username}}</a>
              {% if not message.read %}
                <a class="" data-mid="{{message.mid}}">new</a>
              {% else %}
                <a class="read">read <time-ago datetime="{{message.read.isoformat()}}Z"></time-ago></a>
              {% endif %}
              <a href="#comment-form" class="replycom" data-sub="{{message.sub}}" data-replyto='{{message.username}}' data-post='{{message.pid}}' data-parentid='{{message.mlink}}' data-replytitle='{{message.subject}}' data-mid='{{message.mid}}'>reply</a>
              <a href="{{ url_for('view_comment_inbox', cid=message.mlink) }}" class="btn small">permalink</a>
              <!--<a class="savemsg" data-mid="{{message.mid}}">save</a>-->
              <a class="deletemsg" data-mid="{{message.mid}}">delete</a>
              <a class="block" data-uid="{{message.sentby}}">{% if message.sentby not in func.get_ignores(current_user.uid) %}block{%else%}unblock{%endif%}</a>

            </p>
          </div>
          <div id="replyto{{message.mid}}"><div>
        </article>
      {% endfor %}
    </div>
    {% include 'messages/nav.html' %}
  </div>
</div>

<div id="msgpop" style="display:none;">
  <span class="closemsg">&times;</span>
  <div class="modal-content">
    <form data-reset="true" method="POST" data-redir='true' action="{{url_for('do.create_comment', sub='0', pid='0')}}" class="ajaxform comment-form pure-form pure-form-aligned" id="comment-form">
      {% set commentform = form.PostComment()%}
      {{commentform.csrf_token}}
      {{commentform.post()}}
      {{commentform.parent(value='0')}}
      <h3>Reply to comment from <span id="from"></span> in /{{config.site.sub_prefix}}/<span id="sub"></span></h3>
      <fieldset>
        <div class="pure-control-group markdown-editor">
          {{commentform.comment(placeholder="Styling with Markdown format is supported.", rows="10", **{'data-provide' :"markdown"})}}
        </div>
        <div class="pure-controls">
          {% if error %}
            <div class="error">{{error}}</div>
          {%endif%}
          <button type="submit" id="msg-btnsubmit" class="pure-button pure-button-primary" data-prog="Sending...">Send Comment</button>
        </div>
      </fieldset>
    </form>
  </div>
</div>
{% endblock %}

app/templates/messages/sent.html
{% extends "layout.html" %}
{% block title %}My messages | {{config.site.lema}}{% endblock %}

{% block navbar %}
{% endblock %}

{% block sidebar %}
{{ super() }}
{% include 'messages/sidebar.html' %}
{% endblock %}

{% block content %}
{{ super() }}
<div id="center-container">
  <div class="inbox content">
    <div class="user-activity col-12">
      <h3><span class="p-icon" data-icon="mail" style="display: inline-block;"></span> Sent</h3>
      {% for message in messages %}
        <article class="pmessage post">
          <div class="main">
            <p class="title">{{message.subject}}</p>
            <p class="container">{{markdown(message.content)|safe}}</p>
            <p class="author">&#10148;
              <a href="{{url_for('view_user', user=message.username)}}" class="btn small">/u/{{message.username}}</a>
              <time-ago datetime="{{message.posted.isoformat()}}Z"></time-ago>
            </p>
          </div>
        </article>
      {% endfor %}
    </div>
    {% include 'messages/nav.html' %}
  </div>
</div>
{% endblock %}