app/forms/sub.py
""" Sub-related forms """

from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, BooleanField, HiddenField
from wtforms import RadioField, TextField, SelectField
from wtforms.validators import DataRequired, Length, URL
from wtforms.validators import Optional


class SearchForm(FlaskForm):
    """ Search form """
    term = StringField('Search')


class CreateSubForm(FlaskForm):
    """ Sub creation form """
    subname = StringField('Sub name',
                          validators=[DataRequired(), Length(min=2, max=32)])
    title = StringField('Title',
                        validators=[DataRequired(), Length(min=2, max=50)])

    nsfw = BooleanField('Sub is NSFW?')


class EditSubCSSForm(FlaskForm):
    """ Edit sub stylesheet form. """
    css = TextAreaField('Custom stylesheet', validators=[Length(max=10000)])


class DeleteCommentForm(FlaskForm):
    """ Removes a comment in a post """
    cid = HiddenField()  # comment id
    reason = StringField()


class EditCommentForm(FlaskForm):
    """ Edits a comment in a post """
    cid = HiddenField()  # comment id
    text = TextAreaField('Your comment',
                         validators=[DataRequired(),
                                     Length(min=1, max=16384)])


class CreateSubFlair(FlaskForm):
    """ Creates a flair """
    text = StringField('Flair text', validators=[DataRequired(),
                                                 Length(max=25)])


class EditSubFlair(FlaskForm):
    """ Edits ONE flair from a sub """
    flair = HiddenField()
    text = StringField('Flair text', validators=[DataRequired(),
                                                 Length(max=22)])


class DeleteSubFlair(FlaskForm):
    """ Used to delete flairs """
    flair = HiddenField()


class EditSubForm(FlaskForm):
    """ Edit sub form. """
    title = StringField('Title',
                        validators=[DataRequired(), Length(min=2, max=128)])

    nsfw = BooleanField('Sub is NSFW')
    restricted = BooleanField('Only mods can post')
    usercanflair = BooleanField('Allow users to flair their own posts')
    videomode = BooleanField('Enable video player (youtube links only)')
    polling = BooleanField('Enable polls')
    subsort = RadioField('Default sub page post sorting',
                         choices=[('v', 'Hot'), ('v_two', 'New'),
                                  ('v_three', 'Top')],
                         validators=[Optional()])
    subtags = StringField('Tags')
    sidebar = TextAreaField('Sidebar text',
                            validators=[Length(max=8000)])


class EditMod2Form(FlaskForm):
    """ Edit mod2 of sub (admin/owner) """
    user = StringField('New mod username',
                       validators=[DataRequired(), Length(min=1, max=128)])
    level = SelectField('Mod level', choices=[('1', 'Moderator'), ('2', 'Janitor')], validators=[DataRequired()])


class CreateSubTextPost(FlaskForm):
    """ Sub content submission form """
    sub = StringField('Sub', validators=[DataRequired(),
                                         Length(min=2, max=32)])
    title = StringField('Post title',
                        validators=[DataRequired(), Length(min=3, max=350)])
    content = TextAreaField('Post content',
                            validators=[Length(max=16384)])
    link = StringField('Post link',
                       validators=[Length(min=10, max=256), Optional(),
                                   URL(require_tld=True)])
    ptype = RadioField('Post type',
                       choices=[('text', 'Text post'), ('link', 'Link post'), ('poll', 'Poll post')],
                       validators=[DataRequired()])
    nsfw = BooleanField('NSFW?')
    # for polls.
    hideresults = BooleanField('Hide poll results until it closes')
    closetime = StringField('Poll closing')

    def __init__(self, *args, **kwargs):
        super(CreateSubTextPost, self).__init__(*args, **kwargs)
        try:
            self.sub.data = kwargs['sub']
        except KeyError:
            pass


class CreteSubPostCaptcha(CreateSubTextPost):
    captcha = TextField('Captcha')
    ctok = HiddenField()


class CreateSubLinkPost(FlaskForm):
    """ Sub content submission form """
    sub = StringField('Sub', validators=[DataRequired(),
                                         Length(min=2, max=32)])
    title = StringField('Post title',
                        validators=[DataRequired(), Length(min=4, max=350)])
    link = StringField('Post link',
                       validators=[DataRequired(), Length(min=10, max=256),
                                   URL(require_tld=True)])
    nsfw = BooleanField('NSFW?')

    def __init__(self, *args, **kwargs):
        super(CreateSubLinkPost, self).__init__(*args, **kwargs)
        try:
            self.sub.data = kwargs['sub']
        except KeyError:
            pass


class EditSubTextPostForm(FlaskForm):
    """ Sub content edit form """
    content = TextAreaField('Post content',
                            validators=[DataRequired(),
                                        Length(min=1, max=16384)])


class EditSubLinkPostForm(FlaskForm):
    """ Sub content edit form """
    nsfw = BooleanField('NSFW?')


class PostComment(FlaskForm):
    """ Comment submission form """
    post = HiddenField()
    parent = HiddenField()

    comment = TextAreaField('Your comment',
                            validators=[DataRequired(),
                                        Length(min=1, max=16384)])


class BanUserSubForm(FlaskForm):
    """ Edit ban user from posting """
    user = StringField('username to ban',
                       validators=[DataRequired(), Length(min=1, max=128)])
    reason = StringField('reason for the ban', validators=[DataRequired(), Length(min=1, max=128)])
    expires = StringField('ban expires')


class EditPostFlair(FlaskForm):
    """ Post deletion form. """
    post = HiddenField()
    flair = RadioField('Flair',
                       choices=[],
                       validators=[DataRequired()])


class DeletePost(FlaskForm):
    """ Post deletion form. """
    post = HiddenField()
    reason = StringField()


class VoteForm(FlaskForm):
    """ form for voting """
    post = HiddenField()  # Post PID

app/views/sub.py
import datetime
import time
from flask import Blueprint, redirect, url_for, abort, render_template, request, Response
from flask_login import login_required, current_user
from feedgen.feed import FeedGenerator
from peewee import fn, JOIN
from ..misc import engine
from ..models import Sub, SubMetadata, SubStylesheet, SubUploads, SubPostComment, SubPost, SubPostPollOption
from ..models import SubPostPollVote, SubPostMetadata, SubFlair, SubLog, User, UserSaved, SubMod, SubBan
from ..forms import EditSubFlair, EditSubForm, EditSubCSSForm, EditSubTextPostForm, EditMod2Form
from ..forms import EditSubLinkPostForm, BanUserSubForm, EditPostFlair, CreateSubFlair, PostComment
from .. import misc

sub = Blueprint('sub', __name__)


@sub.route("/<sub>/")
@sub.route("/<sub>")
def view_sub(sub):
    """ Here we can view subs """
    if sub.lower() == "all":
        return redirect(url_for('all_hot', page=1))

    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    try:
        x = SubMetadata.select().where(SubMetadata.sid == sub.sid)
        x = x.where(SubMetadata.key == 'sort').get()
        x = x.value
    except SubMetadata.DoesNotExist:
        x = 'v'
    if x == 'v':
        return redirect(url_for('sub.view_sub_hot', sub=sub.name))
    elif x == 'v_two':
        return redirect(url_for('sub.view_sub_new', sub=sub.name))
    elif x == 'v_three':
        return redirect(url_for('sub.view_sub_top', sub=sub.name))


@sub.route("/<sub>/edit/css")
@login_required
def edit_sub_css(sub):
    """ Here we can edit sub info and settings """
    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    if not current_user.is_mod(sub.sid, 1) and not current_user.is_admin():
        abort(403)

    c = SubStylesheet.get(SubStylesheet.sid == sub.sid)

    form = EditSubCSSForm(css=c.source)
    stor = 0
    ufiles = SubUploads.select().where(SubUploads.sid == sub.sid)
    for uf in ufiles:
        stor += uf.size / 1024

    return engine.get_template('sub/css.html').render({'sub': sub, 'form': form, 'error': False, 'storage': int(stor), 'files': ufiles})


@sub.route("/<sub>/edit/flairs")
@login_required
def edit_sub_flairs(sub):
    """ Here we manage the sub's flairs. """
    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    if not current_user.is_mod(sub.sid, 1) and not current_user.is_admin():
        abort(403)

    flairs = SubFlair.select().where(SubFlair.sid == sub.sid).dicts()
    formflairs = []
    for flair in flairs:
        formflairs.append(EditSubFlair(flair=flair['xid'], text=flair['text']))
    return render_template('editflairs.html', sub=sub, flairs=formflairs,
                           createflair=CreateSubFlair())


@sub.route("/<sub>/edit")
@login_required
def edit_sub(sub):
    """ Here we can edit sub info and settings """
    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    if current_user.is_mod(sub.sid, 1) or current_user.is_admin():
        submeta = misc.metadata_to_dict(SubMetadata.select().where(SubMetadata.sid == sub.sid))
        form = EditSubForm()
        # pre-populate the form.
        form.subsort.data = submeta.get('sort')
        form.sidebar.data = sub.sidebar
        form.title.data = sub.title

        return render_template('editsub.html', sub=sub, editsubform=form, metadata=submeta)
    else:
        abort(403)


@sub.route("/<sub>/sublog", defaults={'page': 1})
@sub.route("/<sub>/sublog/<int:page>")
def view_sublog(sub, page):
    """ Here we can see a log of mod/admin activity in the sub """
    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    logs = SubLog.select().where(SubLog.sid == sub.sid).order_by(SubLog.lid.desc()).paginate(page, 50)
    return engine.get_template('sub/log.html').render({'sub': sub, 'logs': logs, 'page': page})


@sub.route("/<sub>/mods")
@login_required
def edit_sub_mods(sub):
    """ Here we can edit moderators for a sub """
    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    if current_user.is_mod(sub.sid, 2) or current_user.is_modinv(sub.sid) or current_user.is_admin():
        subdata = misc.getSubData(sub.sid, extra=True)
        subMods = misc.getSubMods(sub.sid)
        modInvites = SubMod.select(User.name, SubMod.power_level).join(User).where((SubMod.sid == sub.sid) & (SubMod.invite == True))
        return render_template('submods.html', sub=sub, subdata=subdata,
                               editmod2form=EditMod2Form(), subMods=subMods, subModInvites=modInvites,
                               banuserform=BanUserSubForm())
    else:
        abort(403)


@sub.route("/<sub>/new.rss")
def sub_new_rss(sub):
    """ RSS feed for /sub/new """
    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    fg = FeedGenerator()
    fg.id(request.url)
    fg.title('New posts from ' + sub.name)
    fg.link(href=request.url_root, rel='alternate')
    fg.link(href=request.url, rel='self')
    
    posts = misc.getPostList(misc.postListQueryBase(noAllFilter=True).where(Sub.sid == sub.sid),
                            'new', 1).dicts()

    return Response(misc.populate_feed(fg, posts).atom_str(pretty=True), mimetype='application/atom+xml')


@sub.route("/<sub>/new", defaults={'page': 1})
@sub.route("/<sub>/new/<int:page>")
def view_sub_new(sub, page):
    """ The index page, all posts sorted as most recent posted first """
    if sub.lower() == "all":
        return redirect(url_for('all_new', page=1))

    try:
        sub = Sub.select().where(fn.Lower(Sub.name) == sub.lower()).dicts().get()
    except Sub.DoesNotExist:
        abort(404)

    posts = misc.getPostList(misc.postListQueryBase(noAllFilter=True).where(Sub.sid == sub['sid']),
                             'new', page).dicts()

    try:
        vm = SubMetadata.select().where(SubMetadata.sid == sub['sid']).where(SubMetadata.key == 'videomode').get().value
    except SubMetadata.DoesNotExist:
        vm = 0
    playlist = []
    if vm == '1':
        for post in posts:
            if post['link']:
                yid = misc.getYoutubeID(post['link'])
                if yid is not None:
                    playlist.append(yid)

    return engine.get_template('sub.html').render({'sub': sub, 'subInfo': misc.getSubData(sub['sid']), 'playlist': playlist,
                                                   'posts': posts, 'page': page, 'sort_type': 'sub.view_sub_new',
                                                   'subMods': misc.getSubMods(sub['sid'])})


@sub.route("/<sub>/bannedusers")
def view_sub_bans(sub):
    """ See banned users for the sub """
    try:
        sub = Sub.get(fn.Lower(Sub.name) == sub.lower())
    except Sub.DoesNotExist:
        abort(404)

    user = User.alias()
    created_by = User.alias()
    banned = SubBan.select(user, created_by, SubBan.created, SubBan.reason, SubBan.expires)
    banned = banned.join(user, on=SubBan.uid).switch(SubBan).join(created_by, JOIN.LEFT_OUTER, on=SubBan.created_by_id)
    banned = banned.where((SubBan.sid == sub.sid) & ((SubBan.effective == True) & ((SubBan.expires.is_null(True)) | (SubBan.expires > datetime.datetime.utcnow()) )))
    banned = banned.order_by(SubBan.created.is_null(True), SubBan.created.desc())

    xbans = SubBan.select(user, created_by, SubBan.created, SubBan.reason, SubBan.expires)
    xbans = xbans.join(user, on=SubBan.uid).switch(SubBan).join(created_by, JOIN.LEFT_OUTER, on=SubBan.created_by_id)
    
    xbans = xbans.where(SubBan.sid == sub.sid)
    xbans = xbans.where((SubBan.effective == False) | ((SubBan.expires.is_null(False)) & (SubBan.expires < datetime.datetime.utcnow()) ))
    xbans = xbans.order_by(SubBan.created.is_null(True), SubBan.created.desc(), SubBan.expires.asc())

    return engine.get_template('sub/bans.html').render({'sub': sub, 'banned': banned, 'xbans': xbans,
                                                        'banuserform': BanUserSubForm(), 'submods': misc.getSubMods(sub.sid)})


@sub.route("/<sub>/top", defaults={'page': 1})
@sub.route("/<sub>/top/<int:page>")
def view_sub_top(sub, page):
    """ The index page, /top sorting """
    if sub.lower() == "all":
        return redirect(url_for('all_top', page=1))

    try:
        sub = Sub.select().where(fn.Lower(Sub.name) == sub.lower()).dicts().get()
    except Sub.DoesNotExist:
        abort(404)

    posts = misc.getPostList(misc.postListQueryBase(noAllFilter=True).where(Sub.sid == sub['sid']),
                             'top', page).dicts()

    try:
        vm = SubMetadata.select().where(SubMetadata.sid == sub['sid']).where(SubMetadata.key == 'videomode').get().value
    except SubMetadata.DoesNotExist:
        vm = 0
    playlist = []
    if vm == '1':
        for post in posts:
            if post['link']:
                yid = misc.getYoutubeID(post['link'])
                if yid is not None:
                    playlist.append(yid)

    return engine.get_template('sub.html').render({'sub': sub, 'subInfo': misc.getSubData(sub['sid']), 'playlist': playlist,
                                                   'posts': posts, 'page': page, 'sort_type': 'sub.view_sub_top',
                                                   'subMods': misc.getSubMods(sub['sid'])})


@sub.route("/<sub>/hot", defaults={'page': 1})
@sub.route("/<sub>/hot/<int:page>")
def view_sub_hot(sub, page):
    """ The index page, /hot sorting """
    if sub.lower() == "all":
        return redirect(url_for('all_hot', page=1))
    try:
        sub = Sub.select().where(fn.Lower(Sub.name) == sub.lower()).dicts().get()
    except Sub.DoesNotExist:
        abort(404)

app/templates/donate.html
{% extends "layout.html" %}
{% block title %}Donate - {{config.site.lema}}{% endblock %}

{% block content %}
{{ super() }}
  <div class="content">
    <h1>Donate to Phuks</h1>
    <p>Phuks is run and developed by volunteers. We do not have ads because we do not believe invading
      our user's privacy should be the solution to monetisation, but we do have many ways you can contribute:</p>

    {% if config.site.btc_address %}
      <h3>Donate Bitcoin</h3>
      <a href="https://blockchain.info/address/{{config.site.btc_address}}" target="_blank">{{config.site.btc_address}}</a>
    {%endif %}

    {% if config.site.xmr_address %}
      <h3>Donate Monero</h3>
      {{config.site.xmr_address}}
    {% endif %}
    
    <h3>Donate via PayPal</h3>
    <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
      <input type="hidden" name="cmd" value="_s-xclick">
      <input type="hidden" name="hosted_button_id" value="USR35RXUAX5AW">
      <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
      <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
    </form>
    <h3>Donate something else</h3>
    <p>Phuks is open source! You can contribute with code. <a href="https://phab.phuks.co">Here is our bug tracker</a></p>
    <p>Anything else? Just <a href="mailto:admin@phuks.co">contact us</a>.</p>
  </div>
{% endblock %}

app/templates/editflairs.html
{% extends "layout.html" %}
{% block title %}{{config.site.lema}}{% endblock %}
{% block navbar %}
<ul class="right">
  <li class="large"><a href="{{url_for('sub.view_sub', sub=sub.name)}}">/{{config.site.sub_prefix}}/{{sub.name}}</a></li>
</ul>
{% endblock %}
{% block content %}
{{ super() }}

{% if not current_user.is_mod(sub.sid, 1) and current_user.is_admin() %}
<div class="important"><h3>Editing as Admin</h3></div>
{% endif %}

<h1>Editing /{{config.site.sub_prefix}}/{{sub.name}}'s flairs</h1>
<div class="col-12 admin-page-form">
  <form  method="POST" class="ajaxform pure-form" action="{{url_for('do.create_flair', sub=sub.name)}}" data-reload="true">
    <h4>Create new flair</h4>
    {{createflair.csrf_token}}
      {{createflair.text(placeholder="Flair text")}}
      <button type="submit" class="pure-button pure-button-primary" id="editsub-btnsubmit" data-prog="Saving..." data-success="Saved!">Add flair</button>
    <div class="alert div-error">
      <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
      <p></p>
    </div>
  </form>
</div>

{% if flairs %}
<hr>
<h4>Flairs</h4>
  <div class="col-12 admin-page-form">
    <ul>
    {% for flair in flairs %}
    <li><span class="postflair">{{flair.text.data}}</span>
      <form  method="POST" data-reload="true" action="{{url_for('do.delete_flair', sub=sub.name)}}" class="ajaxform" style="display: inline-block; margin-left: 1em; margin-top: 5px;">
      {{flair.csrf_token}}{{flair.flair}}<button type="submit" class="pure-button button-xsmall" id="editsub-btnsubmit" data-prog="Deleting..." data-success="Deleted!">Delete</button></form>
    {% endfor %}
  </ul>
  </div>
{% endif %}
{% endblock %}

app/templates/indexmulti.html
{% extends "layout.html" %}
{% block title %}Multi - {{config.site.lema}}{% endblock %}

{% block sidebar %}
{{ super() }}
<div class="sidebarlists">
  <h4 class="center">New posts from:</h4>
  <ul>
    
    {% for sub in subs %}
      <li><a href="{{url_for('sub.view_sub', sub=sub.name)}}">/{{config.site.sub_prefix}}/{{sub.name}}</a>
      <div class="sidelocale">{{sub.title}}</div></li>
    {%endfor%}
  </ul>
</div>
{% endblock %}

{% block content %}
{{ super() }}
{% if not posts %}<h1 class="noshit">There are no posts here, yet.</h1>{% endif %}
<div class="alldaposts">
{% for post in posts if post.pid != func.getAnnouncement().pid %}
  {% include "indexpost.html" %}
{%endfor %}
</div>

{% if not kw %}
  {% set kw = {} %}
{%endif%}
{% if page > 1 %}
  <a href="{{url_for(sort_type, page=(page-1), sublist=sublist, **kw)}}" class="pure-button">prev</a>
{% endif %}
{% if posts|length == 25 %}
  <a href="{{url_for(sort_type, page=(page+1), sublist=sublist, **kw)}}" class="pure-button">next</a>
{% endif %}
{% endblock %}

{%block pagefoot%}
{%endblock%}

app/templates/indexpost.html
<div pid="{{post.pid}}" class="{% if post.deleted != 0 %}deletedpost {% endif %}post">
    <div class="misctainer">
      <div class="votebuttons">
        {% if post.userstatus != 10 and (datetime.datetime.utcnow() - post.posted.replace(tzinfo=None)) < datetime.timedelta(days=60) %}
        <div title="Upvote" class="upvote{%if post.positive == 1%} upvoted{%endif%}" data-pid="{{post.pid}}" data-icon="upvote"></div>
        <div class="score">{{post.score}}</div>
        <div title="Downvote" class="downvote{%if post.positive == 0%} downvoted{%endif%}" data-pid="{{post.pid}}" data-icon="downvote"></div>
        {%endif%}
      </div>
      <div class="thcontainer">
        <a href="{{url_for('sub.view_post', sub=post.sub, pid=post.pid)}}" class="title">
          <div class="thumbnail">
            {% if post.thumbnail != '' and post.link != None %}
              <img src="{{config.storage.thumbnails.url}}{{post.thumbnail}}"/>
            {% elif post.link != None %}
              <span class="placeholder" data-icon="link"></span>
            {%else%}
              <span class="placeholder" data-icon="chat"></span>
            {% endif%}

          </div>
        </a>
      </div>
    </div>
    <div class="pbody">
      <div classub.htmlsub.htmls="post-heading">
        {% if post.nsfw %}
        <div class="nsfw" alt="Not safe for work">NSFW</div>
        {%endif%}
        {% if post.flair %}<span class="postflair">{{post.flair}}</span>{% endif %}
        {% if post.link == None %}
          <a href="{{url_for('sub.view_post', sub=post.sub, pid=post.pid)}}" class="title">{{post.title}}</a>
        {% else %}
          {% if post.link.startswith('http:') %}<span title="not https" class="p-icon" data-icon="exclaim"></span>{% endif %}
          <a href="{{post.link}}" class="title">{{post.title}}</a> <a href="{{url_for('all_domain_new', domain=func.getDomain(post.link), page=1)}}" class="domain">({{func.getDomain(post.link)}})</a>
        {% endif %}
      </div>
      <div class="author">
          {% if post.link %}
            {% if func.getDomain(post.link) in ('www.hooktube.com', 'hooktube.com', 'youtube.com', 'www.youtube.com', 'youtu.be', 'gfycat.com', 'vimeo.com', 'vine.co') %}
            <div class="expando" data-pid="{{post.pid}}" data-t="lnk" data-link="{{post.link}}"><div class="icon expando-btn" data-icon="play"></div></div>
            {% elif func.isImage(post.link) %}
            <div class="expando" data-pid="{{post.pid}}" data-t="lnk" data-link="{{post.link}}"><div class="icon expando-btn" data-icon="image"></div></div>
            {% elif func.isVideo(post.link) or func.isGifv(post.link) %}
            <div class="expando" data-pid="{{post.pid}}" data-t="lnk" data-link="{{post.link}}"><div class="icon expando-btn" data-icon="play"></div></div>
            {% endif %}
          {% elif post.content != '' %}
          <div class="expando" data-pid="{{post.pid}}" data-t="txt" data-link="{{post.link}}"><div class="icon expando-btn" data-icon="text"></div></div>
          {% endif %}
        posted <time-ago datetime="{{post.posted.isoformat()}}Z"></time-ago> by
        {% if post.userstatus != 10 %}
          <a class="authorlink" href="{{url_for('view_user', user=post.user)}}">{{post.user}}</a>
        {% endif %}
        {% if sub and post.pid in func.getStickyPid(sub.sid) %}
        - <span class="stick">sticky</span>
        {% endif %}
        {% if not sub %} on
        <a href="{{url_for('sub.view_sub', sub=post.sub)}}">{{post.sub}}</a>
        {%endif%}
      </div>
      <div class="links">
        <a class="comments" href="{{url_for('sub.view_post', sub=post.sub, pid=post.pid)}}">comments {%if post.comments>0%}({{post.comments}}){%endif%}</a>
      </div>
    </div>
</div>

app/templates/oauthorize.html
{% extends "layout.html" %}
{% block content %}
{{ super() }}
<form action="" method="POST" class="white-popup-block">
  <h1>Authorize OAuth provider</h1>
  <input type="hidden" name="confirm" value="yes" />
    <p>Do you want to authorize {{client.name}} to see your email address and username?</p>
  <p><button type="submit" style="margin-top: 4%" class="btn btn-blue" data-prog="Processing...">Yes, authorize!</button></p>
</form>
{%endblock%}

app/templates/userposts.html
{% extends "layout.html" %}
{% block title %}Posts from /u/{{user.name}} | {{config.site.lema}}{% endblock %}

{% block sidebar %}
{{ super() }}
<a href="{{url_for('view_user', user=user.name)}}" class="sbm-post pure-button">{{user.name}}</a>
<a href="{{url_for('view_user_posts', user=user.name)}}" class="sbm-post pure-button">View posts</a>
<a href="{{url_for('view_user_comments', user=user.name)}}" class="sbm-post pure-button">View comments</a>
{% if user.uid == current_user.uid %}
  <a href="{{url_for('view_user_savedposts', user=user.name)}}" class="sbm-post pure-button">View saved posts</a>
{% endif %}
{% endblock %}

{% block content %}
{{ super() }}
{% if sort_type == 'view_user_posts' %}
  <h3>Recent posts</h3>
{% else %}
  <h3>Saved posts</h3>
{% endif %}
{% if not posts %}
  <h3>There are no posts here, yet.</h3>
{% endif %}

<div class="alldaposts">
{% for post in posts %}
  {% include "indexpost.html" %}
{%endfor%}
</div>

{% if page > 1 %}
  <a href="{{url_for(sort_type, page=(page-1), user=user.name)}}" class="pure-button">prev</a>
{% endif %}
{% if posts|length == 25 %}
  <a href="{{url_for(sort_type, page=(page+1), user=user.name)}}" class="pure-button">next</a>
{% endif %}
{% endblock %}